CREATE TABLE towns(
id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
name VARCHAR(50) NOT NULL
);

CREATE TABLE addresses(
id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
address_text TEXT NOT NULL,
town_id INT NOT NULL,
CONSTRAINT fk_town_id FOREIGN KEY (town_id) REFERENCES towns(id)
);

CREATE TABLE departments(
id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
name VARCHAR(50) NOT NULL
);

CREATE TABLE employees(
id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
first_name VARCHAR(50) NOT NULL,
middle_name VARCHAR(50),
last_name VARCHAR(50) NOT NULL,
job_title VARCHAR(50) NOT NULL,
department_id INT NOT NULL,
CONSTRAINT fk_department_id FOREIGN KEY (department_id) REFERENCES departments(id),
hire_date DATE,
salary DECIMAL (10,2) NOT NULL,
address_id INT NOT NULL,
CONSTRAINT fk_address_id FOREIGN KEY (address_id) REFERENCES addresses(id)
);