title: Hyde
email: m.ravanov@gmail.com
description: Interesting description...
destination: docs
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: Marf_72
github_username: MartinRavanov72

exclude:
  [
    _assets,
    node_modules,
    Gemfile,
    Gemfile.lock,
    gulpfile.js,
    package.json,
    package-lock.json,
    README.md,
  ]
# Build settings
plugins:
  - jekyll-feed
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
